spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace