spring:
  jpa:
    datasource:
      url: jdbc:mysql://localhost:3306/seonbae?serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: sggs8822
      driverClassName: com.mysql.cj.jdbc.Driver
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace